Adding bower.json
pioug/md-virtual-repeater pull request #1
Opened 2017-01-27 20:42 UTC by Karankang007

2017-01-31 08:51 UTC, pioug requested changes

2017-01-31 08:51 UTC, pioug commented on README.md
> +*This fork will no longer be maintained once the original library has it's own bower.json.*
Can you undo this change please 🙏

2017-01-31 08:51 UTC, pioug commented on bower.json
> +  "homepage": "https://github.com/Karankang007/md-virtual-repeater"
Maybe you can redirect to my repository `https://github.com/pioug/md-virtual-repeater` if you are not planning to maintain your fork

2017-01-31 08:52 UTC, pioug commented
Hey! I am glad there are still people using Bower 😁  I added few comments to your PR, just details. I will register the package on Bower after merging!

Thanks for your help!

2017-01-31 16:43 UTC, Karankang007 commented on README.md
> +*This fork will no longer be maintained once the original library has it's own bower.json.*
Hey, i will redirect the bower repo, once your git contains bower.json file.

2017-02-01 04:07 UTC, pioug approved these changes

2017-02-01 04:07 UTC, merged

2017-02-01 16:11 UTC, pioug commented
@Karankang007 You can update the bower registry now 👍

2017-02-01 18:34 UTC, Karankang007 commented
Done. "md-virtual-repeater" bower package now points to your repo.

Please update your project ReadMe.md accordingly.